### ISSUE TITLE
Fl_Gl_Window::draw() *must* be overriden. Please refer to the documentation.

### ISSUE THREAD

**Issue by erusyd** [herculon/multiplot#1]
After compiling test_multiplot.cpp and run ./a.out, it complains:
_Fl_Gl_Window::draw() *must* be overriden. Please refer to the documentation._
and no GUI appears.

**Comment by afkrause** [comment]
short question: what FLTK Version do you use? 
I will try to replicate and fix the issue until tomorrow.

**Comment by erusyd** [comment]
libfltk1.3-dev under linux mint 20.3.
I search this package in Ubuntu 20.04, it should be 1.3.4-10build1.

**Comment by afkrause** [comment]
thanks - just replicated it. i will fix the issue today.

**Comment by afkrause** [comment]
should be fixed now. please let me know if the demo works now for you!
thanks again for the feedback!
i still need to fix the codelite workspace and test under windows, but thats for later. i assume you used ./make.sh

best, Andre

**Comment by erusyd** [comment]
It works now. Thanks!
